# Site settings
name: Pankaj M. Dahilkar
email: pankajmdahilkar@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Electronics Engineer, Python, C,Embedded System, Machine Learning, 8 bit 32 bit Microcontrollers"
skills: "Project Developer L-Tech Labs"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://in.linkedin.com/in/pankaj-dahilkar-7b300859
  - title: Facebook
    url: https://facebook.com/pankajdahilkar
  - title: twitter
    url: https://twitter.com/D_Pankaj4u
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
